# 任务1: 汇总日志检索配置
# --------------------------
# 汇总日志文件根目录
logDirectory: "/data/alipms/dns/fanzhaDnsLog_all/"

# 查询域名
# 支持精确域名、泛域名（*.test.com）搜索；支持配置单个或多个域名
# 格式示例: 
#   queryDomain: "www.test.com"  (单个)
#   queryDomain: ["www.test.com", "*.test.com"] (多个)
queryDomain: ["epdg.epc.mnc011.mcc460.pub.3gppnetwork.org", "*.test.com"]

# 查询源IP
# 支持精确IP、网段（192.168.1.0/24）、IP范围（192.168.1.0-192.168.1.255）搜索；支持配置单个或多个
# 格式示例:
#   sourceIP: "192.168.1.5" (单个)
#   sourceIP: ["192.168.1.5", "192.168.2.0/24"] (多个)
sourceIP: []

# 查询时间 (queryTime_hour 和 queryTime_day 不能同时为空)
# 精确至小时 (格式: YYYYMMDDHH)
queryTime_hour:
#  - "2025062619"
#  - "2025062620"

# 精确至天 (格式: YYYYMMDD)
queryTime_day:
  - "20250626"


# 任务2: 原始日志检索配置
# --------------------------
# 是否同时检索原始日志 ("yes" 或 "no")
isQueryNativeLog: "yes"

# 原始日志文件存放目录 (isQueryNativeLog为 "no" 时不生效)
nativeLogLoc: "/data/dnsLog_bakup/"

# 原始日志检索结果存放目录 (isQueryNativeLog为 "no" 时不生效)
# 如果留空，将自动生成一个默认目录，例如: ./k9364.vip_20250626/
nativeLogResultLoc: "./"
# 汇总日志保存结果，sourceIP为空时生效
aggregatedLogResultLoc: "./"


# 全局配置
# --------------------------
# 并发处理的 worker 数量 (建议根据CPU核心数设置，如 4, 8, 16)
# 如果设置为 0 或负数，程序将使用默认值 10
workerPoolSize: 4

# 指定绑定的 CPU 核心 ID 列表 (例如: [0, 1, 2, 3])
# 如果留空或列表为空，则不进行核心绑定
coreIds: []